Users crud
gabrielcancio/bills-io pull request #3
Opened 2024-02-21 19:53 UTC by Andrevictor20

Foi adicionado 3 novas rotas para a realização do CRUD do usuário: create-users (para criar um novo usuário no banco de dados), get-users (para buscar um usuário existente no banco de dados), delete-users ( para remover um usuário do banco de dados). A rota create-users possui uma verificação para saber se um usuário já existe no banco de dadose se não houver cria o usuário e retorna a mensagem de confirmação, a rota get-users faz a busca do usuário pelo ID e retorna uma mensagem contendo o nome e cpf do usuário e a rota delete-users também faz a busca do usuário pelo ID e retorna uma mensagem de confirmação do usuário deletado com as informações do ID e nome dele. Todas as rotas possuem tratamento de erro, no caso da rota delete-users se um usuário já foi deletado ele irá exibir "Record to delete does not exist.". Além disso foram feitas alterações no schema.prisma e consequentemente na migration do create table user, as mudanças foram : Alterções no tipo do id e do cpf que passaram a ser String , pois anteriormente haviam conflitos ao usar as rotas em relação à tipagem ( ocasionada pelo Zod)

2024-02-22 14:31 UTC, gabrielcancio requested changes
Testei as rotas e nenhuma ta funcionando. Necessário rever os pontos comentados e corrigir o código.

2024-02-22 14:31 UTC, gabrielcancio commented on prisma/schema.prisma
> +  @@map("user")
Nome da tabela deve estar no plural. Seria "users " no caso.

2024-02-22 14:31 UTC, gabrielcancio commented on prisma/schema.prisma
> +  createdAt DateTime @default(now())
Os campos da tabela no campo devem ser apenas snake_case e o camelCase apenas para objetos JS/TS. Para fazer isso é só usar a função `@map` nos campos conforme a documentação do Prisma: https://www.prisma.io/docs/orm/prisma-schema/data-model/models#mapping-model-names-to-tables-or-collections

2024-02-22 14:31 UTC, gabrielcancio commented on prisma/schema.prisma
> +  binaryTargets = "debian-openssl-3.0.x"
Qual a finalidade desse binaryTargets? Ocasionou erro ao tentar o docker no meu ambiente local

2024-02-22 14:31 UTC, gabrielcancio commented on prisma/schema.prisma
>  model TabelaTeste {
Remover esta tabela de teste e toda a rota referente a teste. Ela só servia para testar se o servidor e a conexão com o banco.

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/routes/create-users.ts
> +          user:{
Creio que não seria necessário devolver o usuário. Imagine o cenário em que um usuário malicioso esteja tentando descobrir o id de usuário específico. Dessa forma estaríamos entregando de bandeja. Creio que só a mensagem é suficiente

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/routes/create-users.ts
> +      return reply.status(500).send({
Precisa melhorar esse tratamento de erro, desse jeito os erros gerados pelo zod na validação dos campos da request seriam retornados como erro 500 Internal Server Error, sendo que um erro dessa natureza seria um 400 Bad Request. 

Erros 500 Internal Server Error, são erros inesperados ocasionados pelo mal funcionamento de uma biblioteca ou de código, problemas de conexão com o banco ou qualquer coisa que estejam foram do nosso  controle ou expectativa.

Erros 400 Bad Request são erros relacionados a request que impedem a mesma de ser finalizada com sucesso, como por exemplo inputs indevidos, neste caso o usuário já existia e por tanto não foi concluída com sucesso. Faltar um input necessário também configura Bad Request.

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/routes/delete-user.ts
> +      return reply.status(201).send({
HTTP Status code 201 Created é para justamente uma requisão que obteve sucesso ao efetuar uma requisição que cria algum recurso no servidor. Outros métodos seriam mais adequados como 200 OK, 202 Accepted ou até mesmo 204 No Content se não houver conteúdo na response. Link para doc falando sobre delete requests: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE e Link para doc de HTTP Status https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/routes/get-users.ts
> +      return reply.status(201).send({ user: user});
Aqui o HTTP Status Code correto deveria ser 200 OK

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/server.ts
> +app.register(createUsers)
Está faltando a rota de alteração de dados do usuário.

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/server.ts
>  app.register(teste)
Remover rota de teste

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/routes/get-users.ts
> +      userId: z.string().uuid(),
Rota de get-users não está funcionando. Na validação do query param da request ele ta tentando validar um uuid sendo que o campo id no banco é inteiro.

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/routes/update-users.ts
> +        userId: z.string().uuid(),
Validação por uuid falhando devido ao userId ser um integer

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/routes/delete-user.ts
> +      return reply.status(500).send({ message: error.meta.cause})
error.meta é undefined, não está devolvendo nem o erro correto. Pelo visto não existe um padrão para o json da reponse, em alguns tem messaga outros tem error, necessário definir um padrão. Substituir onde houver error.meta no código.

2024-02-22 14:31 UTC, gabrielcancio commented on src/infra/http/routes/update-users.ts
> +      const { name, email } = updateDataUserSchema.parse(request.body);
Desse jeito a request vai falhar se o usuário quiser alterar apenas um dos, os campos tem que ser opcionais.

2024-02-22 15:27 UTC, Andrevictor20 commented on prisma/schema.prisma
> +  binaryTargets = "debian-openssl-3.0.x"
Ocasionou um erro em minha máquina (Linux) ao tentar executar o código, e o próprio prisma recomendou adicionar o binaryTargets e salvar, dessa forma consegui executar na minha máquina.

2024-02-22 15:28 UTC, Andrevictor20 commented on prisma/schema.prisma
>  model TabelaTeste {
OK.

2024-02-22 15:29 UTC, Andrevictor20 commented on src/infra/http/routes/create-users.ts
> +          user:{
Irei remover, estava apenas testando se ele devolveria o usuário corretamente.

2024-02-22 15:31 UTC, Andrevictor20 commented on src/infra/http/routes/update-users.ts
> +      const { name, email } = updateDataUserSchema.parse(request.body);
Acho melhor na verdade alterar apenas o email, dificilmente alguém alteraria o nome, vou ajustar também.

2024-02-24 14:13 UTC, gabrielcancio requested changes
Mais uma leva de correções para fazer.

2024-02-24 14:13 UTC, gabrielcancio commented on docker-compose.yaml
> +      - '5433:5433'
Commitou as alterações de porta do docker, isso é apenas na sua máquina. O bind de portas está errado, ta fazendo o bind na porta 5433 da tua máquina e na porta 5433 do container, mas dentro do container o postegres roda na 5432, se tu tentar usar um cliente externo de postgres ele não vai funcionar (Exceto o Prisma Studio).

2024-02-24 14:13 UTC, gabrielcancio commented on prisma/schema.prisma
> +  createdat DateTime @default(now())
Aqui continua errado kkk. O padrão para as nomes de campos e tabelas no banco é snake_case, ou seja tudo em minusculo e mais de uma palavra separada por vírgula, como por exemplo `createdAt`, ficaria `created_at`. Entretanto no javascript deveria continuar camelCase, ou seja createdAt continuaria desse mesmo jeito dentro do javascript.

Mas como fazer isso?
Bom eu falei que de modo semelhante ao nome da tabela, da para usar o `@map` para renomear apenas o nome da coluna no banco e continuar do jeito declarado no javascript. Mais uma vez, segue o link para doc: https://www.prisma.io/docs/orm/reference/prisma-schema-reference#map

2024-02-24 14:13 UTC, gabrielcancio commented on src/infra/http/routes/update-users.ts
> +      const { name, email } = updateDataUserSchema.parse(request.body);
Rapaz supondo que a pessoa errou o nome na hora de se cadastrar e não percebeu(Facilmente eu faria isso), a pessoa vai ter que deletar a conta se quiser colocar o nome correto kkkk. Creio é valido manter a alteração do nome.

2024-02-24 14:13 UTC, gabrielcancio commented on src/infra/http/routes/create-users.ts
> +      return reply.status(400).send({
Com relação ao tratamento de erros, ou falei que deveria ser melhor. No caso queria mais especificidade, poder destinguir erros internos de bad request e assim por diante, desse modo tu só tirou o erro 500 e substituiu pelo 400. É preciso ser mais específico. Esse deixa para a gente fazer em pair (Call).

2024-02-24 14:13 UTC, gabrielcancio commented on src/infra/http/routes/get-users.ts
> +export async function getUsers(app: FastifyInstance) {
Creio que o nome getUser ficaria melhor, pois tu está retornando apenas os dados de um usuário em específico. getUsers da impressão que tu está listando todos os usuários.

Escolher nomes corretos é essencial. O nome precisa em pouquíssimas palavras dar uma clara idéia do que aquele código faz. 

Código legível é um dos pontos que separam os bons programadores de maus programadores porque em uma empresa você não está fazendo código para você, está fazendo para os outros. Quando outra pessoa, ou até mesmo você voltar nesse código no futuro não vai se lembrar 100% do contexto. Nomes ambíguos vão confundir e fazer que você tenha mais trabalho para entender o funcionamento do código para melhorá-lo ou corrigi-lo dimunindo a produtividade do time em geral.

2024-02-24 14:13 UTC, gabrielcancio commented on src/infra/http/routes/get-users.ts
> +    if(user){
Recomendo evitar o uso de else o máximo possível, pois quantos mais elses associados a  ifs você tiver, aumenta um negócio chamado [complexidade cliclomática ](https://www.treinaweb.com.br/blog/complexidade-ciclomatica-analise-estatica-e-refatoracao), que basicamente falando seria você criar um labirinto de tantos ifs e elses que você usa que dificulta muito o entendimento do código, por isso é bom evita-lo.

Um truque para se guiar em quando se trata de compexlidade ciclomática é que o código deve estar o mais próximo da margem quanto possível.

Dúvidas pergunte.

2024-02-24 14:13 UTC, gabrielcancio commented on src/infra/http/routes/update-users.ts
> +      return reply.status(201).send({
Continua usando o HTTP Status Code 201 created, que deve ser usado apenas para quando um recurso é criado.

Trocar por 200 OK ou 202 Accepted.

2024-03-02 15:48 UTC, gabrielcancio approved these changes

2024-03-02 15:48 UTC, merged